### ISSUE TITLE
Error when signing in with username on telegram

### ISSUE THREAD

**Issue by yncyrydybyl** [polychatproject/polychat-appservice#16]
We have tried to create a room and then signing in with telegram.
After setting the name and pressing the "join with telegram" button we receive a 500er.

The logfile says:

```
Feb 19 19:43:22 alpha matrix-appservice-polychat[1404058]: {"level":40,"time":1708368202081,"pid":1,"hostname":"2b8b0de9c845","name":"api","err":{"type":"Error","message":"E_OUT_OF_SUB_ROOMS","stack":"Error: E_OUT_OF_SUB_ROOMS\n    at <an
onymous> (/app/src/index.ts:19:16)\n    at claimSubRoom (/app/src/index.ts:13:36)\n    at <anonymous> (/app/src/api.ts:107:41)\n    at <anonymous> (/app/src/api.ts:80:90)\n    at handle (/app/node_modules/express/lib/router/layer.js:54:9)
\n    at next (/app/node_modules/express/lib/router/route.js:62:29)\n    at done (/app/node_modules/multer/lib/make-middleware.js:21:13)\n    at indicateDone (/app/node_modules/multer/lib/make-middleware.js:25:15)\n    at <anonymous> (/ap
p/node_modules/multer/lib/make-middleware.js:129:21)\n    at emit (native)\n    at emitCloseNT (node:stream:1405:25)\n    at processTicksAndRejections (:12:39)","originalLine":19,"originalColumn":16},"msg":"API: Error claiming a sub room 
for !IkLDrPLhRONnjvrZTt:polychat.de for telegram"}
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: {"level":30,"time":1708368207391,"pid":1,"hostname":"2b8b0de9c845","name":"matrix-bot-sdk","msg":"Processing transaction 36678","module":"Appservice"}
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: {"level":30,"time":1708368207393,"pid":1,"hostname":"2b8b0de9c845","name":"matrix-bot-sdk","msg":"Processing event of type m.room.member","module":"Appservice"}
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: {"level":50,"time":1708368207403,"pid":1,"hostname":"2b8b0de9c845","name":"matrix-bot-sdk","msg":"(REQ-51)","errcode":"M_FORBIDDEN","error":"Application service has not registered
 this user (@polychat_0000000007:polychat.de)","module":"MatrixHttpClient"}
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 10 |      * Creates a new Matrix Error
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 11 |      * @param body The error body.
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 12 |      * @param statusCode The HTTP status code.
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 13 |      */
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 14 |     constructor(body, statusCode) {
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: 15 |         super();
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]:              ^
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]: error: M_FORBIDDEN: Application service has not registered this user (@polychat_0000000007:polychat.de)
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]:       at new MatrixError (/app/node_modules/matrix-bot-sdk/lib/models/MatrixError.js:15:9)
Feb 19 19:43:27 alpha matrix-appservice-polychat[1404058]:       at /app/node_modules/matrix-bot-sdk/lib/http.js:95:15
Feb 19 19:43:27 alpha systemd[1]: matrix-appservice-polychat.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by yncyrydybyl** [comment]
And again the agent @00000007
